# Generated by Django 3.2.5 on 2021-07-07 19:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('L’Île-Bizard—Sainte-Geneviève', 'L’Île-Bizard—Sainte-Geneviève'), ('Pierrefonds-Roxboro', 'Pierrefonds-Roxboro'), ('Saint-Laurent', 'Saint-Laurent'), ('Ahuntsic-Cartierville', 'Ahuntsic-Cartierville'), ('Montréal-Nord', 'Montréal-Nord'), ('Rivière-des-Prairies—Pointe-aux-Trembles', 'Rivière-des-Prairies—Pointe-aux-Trembles'), ('Anjou', 'Anjou'), ('Saint-Léonard', 'Saint-Léonard'), ('Villeray—Saint-Michel—Parc-Extension', 'Villeray—Saint-Michel—Parc-Extension'), ('Rosemont—La Petite-Patrie', 'Rosemont—La Petite-Patrie'), ('Mercier—Hochelaga-Maisonneuve', 'Mercier—Hochelaga-Maisonneuve'), ('Le Plateau-Mont-Royal', 'Le Plateau-Mont-Royal'), ('Outremont', 'Outremont'), ('Ville-Marie', 'Ville-Marie'), ('Côte-des-Neiges—Notre-Dame-de-Grâce', 'Côte-des-Neiges—Notre-Dame-de-Grâce'), ('Le Sud-Ouest', 'Le Sud-Ouest'), ('Verdun', 'Verdun'), ('LaSalle', 'LaSalle')], max_length=50)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('organizations', multiselectfield.db.fields.MultiSelectField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('clean', 'Clean'), ('cook', 'Cook'), ('serve', 'Serve'), ('prep', 'Prep'), ('garden', 'Garden'), ('delivery', 'Delivery'), ('education', 'Education'), ('warehouse', 'Warehouse'), ('daycare', 'Day care'), ('sort', 'Sort')], max_length=50)),
            ],
        ),
    ]
