# Generated by Django 3.2.5 on 2021-07-07 20:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_input',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('L’Île-Bizard—Sainte-Geneviève', 'L’Île-Bizard—Sainte-Geneviève'), ('Pierrefonds-Roxboro', 'Pierrefonds-Roxboro'), ('Saint-Laurent', 'Saint-Laurent'), ('Ahuntsic-Cartierville', 'Ahuntsic-Cartierville'), ('Montréal-Nord', 'Montréal-Nord'), ('Rivière-des-Prairies—Pointe-aux-Trembles', 'Rivière-des-Prairies—Pointe-aux-Trembles'), ('Anjou', 'Anjou'), ('Saint-Léonard', 'Saint-Léonard'), ('Villeray—Saint-Michel—Parc-Extension', 'Villeray—Saint-Michel—Parc-Extension'), ('Rosemont—La Petite-Patrie', 'Rosemont—La Petite-Patrie'), ('Mercier—Hochelaga-Maisonneuve', 'Mercier—Hochelaga-Maisonneuve'), ('Le Plateau-Mont-Royal', 'Le Plateau-Mont-Royal'), ('Outremont', 'Outremont'), ('Ville-Marie', 'Ville-Marie'), ('Côte-des-Neiges—Notre-Dame-de-Grâce', 'Côte-des-Neiges—Notre-Dame-de-Grâce'), ('Le Sud-Ouest', 'Le Sud-Ouest'), ('Verdun', 'Verdun'), ('LaSalle', 'LaSalle')], max_length=60),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='organizations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=60),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('clean', 'Clean'), ('cook', 'Cook'), ('serve', 'Serve'), ('prep', 'Prep'), ('garden', 'Garden'), ('delivery', 'Delivery'), ('education', 'Education'), ('warehouse', 'Warehouse'), ('daycare', 'Day care'), ('sort', 'Sort')], max_length=60),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=60),
        ),
    ]
